
server:
  port: 10001
dubbo:
  application:
    name: user-consumer
  registry:
    address: zookeeper://127.0.0.1:2181


#  registry:
#    address: 127.0.0.1
#    port: 2181
#    protocol: zookeeper