
server:
  port: 10000
dubbo:
  application:
    name: user-service
  protocol:
    port: 20880
  registry:
    address: zookeeper://127.0.0.1:2181


#  registry:
#    address: 127.0.0.1
#    port: 2181
#    protocol: zookeeper